[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = "next"

# The default session, also known as the greeter.
[default_session]

# `tuigreet` is a "terminal-ish" greeter that will run startx
command = "tuigreet --time --remember --remember-session --asterisks --greeting 'Access is restricted to authorized personnel only.'"

# The user to run the command as.
user = "greeter"
