#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

DIR=$(readlink -f "$(dirname "$0")")
cd "$DIR" || exit 1

if ! command -v sudo >/dev/null 2>&1; then
  echo "Command missing: sudo"
  exit 1
fi

while getopts ":k:m:" opt; do
  case ${opt} in
    k)
      KIND="$OPTARG"
      ;;
    m)
      MODULE="$OPTARG"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}"
      exit 1
      ;;
  esac
done

if [[ ! -v KIND ]]; then
  echo "Missing parameter: kind"
  exit 1
fi

if [[ ! -x "setup/${KIND}" ]]; then
  echo "Unsupported system kind: ${KIND} not in [$(ls setup)]"
  exit 1
fi

set +eo pipefail
read -s -p "What's your sudo password for escalation? " BECOME_PASSWORD
echo "$BECOME_PASSWORD" | sudo -S -p "command" -v &>/dev/null
if [[ $? -ne 0 ]]; then
  echo -e "\nFailed to authenticate with sudo"
  exit 1
fi
echo ""
set -eo pipefail

export SUDO_PROMPT="Your sudo session expired, please enter the password again: "
source "./setup/${KIND}" >/dev/null

EXTRA_VARS=("kind='$KIND'")
if [[ -v MODULE && -n "$MODULE" ]]; then
  EXTRA_VARS+=("module='$MODULE'")
fi
EXTRA_VARS=$(echo "${EXTRA_VARS[@]}")

echo "$BECOME_PASSWORD" | ansible-playbook install.yml --extra-vars="$EXTRA_VARS" --become-password-file=/bin/cat
