[project]
name = "kickstart"
version = "0.0.0"
requires-python = ">=3.12.11"
readme = "README.md"
dependencies = [
    "pyinfra>=3.4.1",
]

[project.urls]
Repository = "https://github.com/bruno-delfino1995/kickstart"

[dependency-groups]
dev = [
    "ruff>=0.12.4",
]
