#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

DIR=$(readlink -f "$(dirname "$0")")
cd "$DIR" || exit 1

if ! command -v mise >/dev/null 2>&1; then
  echo "Command missing: mise"
  exit 1
fi

mise install
mise run deps
