---
- name: Set source and destination
  set_fact:
    src: "{{ role_path }}/links"
    dest: "$HOME"

- name: Find directories
  find:
    paths: "{{ src }}"
    file_type: directory
    hidden: true
    recurse: true
    patterns: "*"
  register: directories

- name: Create directories
  file:
    path: "{{ dest }}/{{ item }}"
    state: directory
  loop: "{{ directories.files | flatten(levels=1) | map(attribute='path') | map('regex_replace', '^' + src + '/(.+)$', '\\1') }}"

- name: Find files
  find:
    paths: "{{ src }}"
    file_type: file
    hidden: true
    recurse: true
    patterns: "*"
  register: files

- name: Link files
  file:
    force: true
    state: link
    src: "{{ item }}"
    dest: "{{ dest }}/{{ file }}"
  loop: "{{ files.files | flatten(levels=1) | map(attribute='path') }}"
  vars:
    file: "{{ item | regex_replace('^' + src + '/(.+)$', '\\1') }}"
  loop_control:
    label: "{{ file }}"

- name: Find links
  find:
    paths: "{{ src }}"
    file_type: link
    hidden: true
    recurse: true
    patterns: "*"
  register: links

- name: Link links
  file:
    force: true
    state: link
    src: "{{ item }}"
    dest: "{{ dest }}/{{ file }}"
  loop: "{{ links.files | flatten(levels=1) | map(attribute='path') }}"
  vars:
    file: "{{ item | regex_replace('^' + src + '/(.+)$', '\\1') }}"
  loop_control:
    label: "{{ file }}"

- name: Copy base git index
  copy:
    src: "{{ role_path }}/tmpls/.config/gitconfig.d/00-index"
    dest: "$HOME/.config/gitconfig.d/00-index"
    force: false

- name: Import public key
  command: gpg --recv-keys '69755601B3AFF040439A1BB1F4EF91F02AACA9DF'
  changed_when: false
