---
- name: Update database
  become: true
  pacman:
    update_cache: true

- name: Install mirrors updater
  become: true
  pacman:
    name: reflector

- name: Optimize mirrors
  become: true
  block:
    - name: Check mirrorlist contents
      command: cat /etc/pacman.d/mirrorlist
      register: contents
      changed_when: false

    - name: Check mirrorlist age
      stat:
        path: /etc/pacman.d/mirrorlist
      register: stats
      changed_when: false

    - name: Refresh mirrorlist
      command: reflector --protocol https --age 48 --latest 100 --fastest 50 --save /etc/pacman.d/mirrorlist
      when: |
        contents.stdout.find('Reflector') == -1
        or
        (ansible_date_time.epoch|int - stats.stat.mtime) > (7 * 60 * 60 * 24)

- name: Enable mirrorlist auto-update
  become: true
  systemd:
    name: reflector.timer
    enabled: true
    state: started

- name: Place sysfiles
  become: true
  copy:
    src: sysfiles/
    dest: /
