#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

DIR=$(realpath "$(dirname "$0")")

cd "$DIR" || exit 1

eval "$(docopts -h - : "$@" <<EOF
Configures your system with modules

Usage:
  machine install [<module>]
EOF
)"

function ansible::dep() {
  ansible-galaxy install -r requirements.yml > /dev/null
}

function ansible::run () {
	if [[ -n "$module" ]]; then
		ansible-playbook -K playbook.yml --extra-vars="modules=['$module']"
	else
		ansible-playbook -K playbook.yml
	fi
}

ansible::dep
ansible::run
