#!/usr/bin/env bash

if ! command -v pacman > /dev/null 2>&1; then
  echo "Command missing: pacman"
  exit 1
fi

if ! pacman -Qi ansible &>/dev/null; then
  sudo pacman -S ansible
fi

ansible-galaxy install luizgavalda.aur,v0.43
