---
- name: Install audio back-end
  become: true
  pacman:
    name:
      - pipewire
      - pipewire-audio
      - pipewire-alsa
      - pipewire-pulse
      - wireplumber

- name: Install audio GUI
  become: true
  pacman:
    name: pavucontrol

- name: Install bluetooth back-end
  become: true
  pacman:
    name:
      - bluez
      - bluez-utils

- name: Install bluetooth GUI
  become: true
  pacman:
    name: blueman

- name: Enable bluetooth service
  become: true
  systemd:
    name: bluetooth
    enabled: true
    state: started

- name: Install PlayerCTL
  become: true
  pacman: name=playerctl
