---
- name: Check brew existence
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Installing Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when:
    - not homebrew_check.stat.exists

- name: Install GnuPG tools
  homebrew:
    name:
      - gnupg
      - hopenpgp-tools

- name: Install pinentry
  homebrew:
    name: pinentry-mac

- name: Link pinentry
  become: true
  file:
    src: "/usr/local/bin/pinentry-mac"
    dest: "/usr/local/bin/pinentry-proxy"
    state: link

- name: Install SmartCard tools
  homebrew:
    name: yubikey-personalization

- name: Install ZSH
  homebrew:
    name: zsh

- name: Install shell prompt
  homebrew:
    name: starship
